version: "3.8"

services:
  flowgate:
    build: .
    container_name: flowgate
    ports:
      - "8080:8080"
    depends_on:
      - dummy-backend
      - order-service-1
      - redis
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - GEMINI_API_KEY=${GEMINI_API_KEY}

  flowgate-2:
    build: .
    container_name: flowgate-2
    ports:
      - "8081:8080"
    depends_on:
      - dummy-backend
      - order-service-1
      - redis
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - GEMINI_API_KEY=${GEMINI_API_KEY}

  nginx:
    image: nginx:1.27-alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - flowgate
      - flowgate-2

  dummy-backend:
    image: kennethreitz/httpbin
    container_name: dummy-backend
    ports:
      - "9000:80"

  order-service-1:
    image: hashicorp/http-echo
    container_name: order-service-1
    command: ["-text=hello from order-service-1"]
    ports:
      - "9001:5678"

  order-service-2:
    image: hashicorp/http-echo
    container_name: order-service-2
    command: ["-text=hello from order-service-2"]
    ports:
      - "9002:5678"

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"