events {}

http {
    upstream flowgate_backend {
        least_conn;                      # nginx's own load-balancing strategy — explained below
        server flowgate:8080;
        server flowgate-2:8080;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://flowgate_backend;
            proxy_http_version 1.1;

            # Required for WebSocket connections (our dashboard's /ws/events) to work through nginx
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}