management:
  endpoints:
    web:
      exposure:
        include: prometheus,health
  endpoint:
    health:
      show-details: always

server:
  port: 8080

spring:
  application:
    name: flowgate
  data:
    redis:
      host: redis     # container/service name — same DNS trick from Phase 0's bug fix
      port: 6379

flowgate:
  jwt:
    secret: ".."
  routes:
    - id: order-service
      path-pattern: "/orders/**"
      target-uris:
        - "http://order-service-1:5678"
        - "http://order-service-2:5678"
      health-check-path: "/"
      load-balancing-strategy: "round-robin"
    - id: dummy-backend
      path-pattern: "/**"
      target-uris:
        - "http://dummy-backend:80"
      health-check-path: "/status/200"